### ISSUE TITLE
Add a Babel option, seperate Babel from React

### ISSUE THREAD

**Issue by spartanatreyu** [jakoblind/webpack-autoconf#5]
Not every project that uses Babel will use React (eg. Angular, Vue, etc...), so we can start by replicating React's config for Babel:

```bash
npm install --save-dev webpack react react-dom babel-loader babel-preset-react babel-core babel-preset-env
```

then remove the react related node modules from the above command.

**Comment by jakoblind** [comment]
Good idea! I am not familiar with Vue or Angular. When reading the docs for vue I see there is something called `vue-loader` that is used for the `.vue` files. And `babel-loader` is used for `.js` files. Is it common to mix js-files and vue-files in a vue project?

**Comment by spartanatreyu** [comment]
I'm not sure how common it is but it seems reasonable to expect devs will want to mix in js for libraries and other ported code. It wouldn't make sense in every situation to wrap _everything_ inside a vue component.

**Comment by infomaniac50** [comment]
When I write code in Vue files it's because I can group everything together. Most new code can be put into Vue files. If you have alot of legacy code it can be difficult to port everything. For example, you can't run Vue files through Twig templates.

https://vue-loader.vuejs.org/guide/pre-processors.html

> vue-loader allows you to use other webpack loaders to process a part of a Vue component. It will automatically infer the proper loaders to use based on the lang attribute of a language block and the rules in your webpack config.

Vue files group related code all in one place. vue-loader isn't much more than a proxy for other loaders. You can use regular ES5 javascript in the script tag of a Vue file. However browsers are becoming more ES6 aware and I use Babel.js quite often.

According to https://vue-loader.vuejs.org/spec.html#script

> Any webpack rules that match against .js files (or the extension specified by the lang attribute) will be applied to contents in the <script> block as well.

You don't have to use Babel in the script block though. You can use whatever Javascript processor you like. https://vue-loader.vuejs.org/guide/pre-processors.html#typescript I suppose you could even use coffeescript.

vue-loader is a recursive process. You can have all of the options you would with separate files and still have related code grouped together in a single file.

I agree with @spartanatreyu that Babel.js should be separated into a new checkbox. I have never used React but I almost always use Babel. The two thing I commonly use Babel for are Classes and Module Imports.

**Comment by jakoblind** [comment]
Great inpu @infomaniac50 . I learn alot about Vue :) 

Based on the discussion, I think it would make sense to add two new checkboxes: "Vue" and "Babel":
![image](https://user-images.githubusercontent.com/399339/39802649-df33e650-536e-11e8-95ab-8dbd7bdef945.png)

When clicking Vue, you would automatically get babel config js files. I am working on this now

**Comment by infomaniac50** [comment]
I created a project to see what vue-cli generates from the webpack-simple template.

This gist outlines the choices I made and the contents of webpack.config.js https://gist.github.com/infomaniac50/34255dfbfdf46476de7d0e2248b400af

https://github.com/vuejs-templates/webpack-simple
https://github.com/vuejs/vue-cli

**Comment by infomaniac50** [comment]
Also be aware that Vue Loader v15 now requires an accompanying webpack plugin to function properly.

It looks like Vue Loader v15 was released 15 days ago. New webpack configs should probably use the plugin. However the webpack-simple template does seem to be updated yet. It does use an old version though so it shouldn't be broken. "vue-loader": "^13.0.5"

```javascript
// webpack.config.js
const VueLoaderPlugin = require('vue-loader/lib/plugin')

module.exports = {
  // ...
  plugins: [
    new VueLoaderPlugin()
  ]
}
```
https://vue-loader.vuejs.org/migrating.html#a-plugin-is-now-required

**Comment by jakoblind** [comment]
Babel is separated to it's own checkbox. Closing this
